//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public CLIENTES()
        {
            this.VENTA = new HashSet<VENTA>();
        }
    
        public int codCliente { get; set; }
        public string Nombre { get; set; }
        public string genero { get; set; }
    
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
