//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int idVenta { get; set; }
        public Nullable<int> codCliente { get; set; }
        public Nullable<int> idLibro { get; set; }
        public decimal importeBruto { get; set; }
        public decimal montoDescuento { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual LIBRO LIBRO { get; set; }
    }
}
